version: "3.8"

services:
  controller:
    container_name: nenc_controller
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-Controller
    ports:
      - "8083:80"

  redis:
    container_name: nenc_redis
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

volumes:
  redis_data:
    driver: local