FROM python:3.10

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

# Shared Files
COPY ./config.py /app/config.py
COPY ./datastore.py /app/datastore.py

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers"]